### ISSUE TITLE
Supporting python3

### ISSUE THREAD

**Issue by laixintao** [laixintao/git-ext#14]

**Comment by laixintao** [comment]
```
(gitext)  ~/Program/git-ext   master  python git_ext/bin/pullrequest.py
Traceback (most recent call last):
  File "git_ext/bin/pullrequest.py", line 11, in <module>
    from git_ext.utils import logging, get_reviewers_group, check_reviewers_group
  File "/Users/laixintao/program/git-ext/git_ext/__init__.py", line 10, in <module>
    from git_ext.git import get_repo_slug
  File "/Users/laixintao/program/git-ext/git_ext/git.py", line 12, in <module>
    import commands
ModuleNotFoundError: No module named 'commands'
```

**Comment by laixintao** [comment]
finally fixed!

https://github.com/laixintao/git-ext/commit/332cbd27e04e5495f79503421013db2a6fbe77c6
